import React from "react";
import {
  Button,
  Cascader,
  Checkbox,
  DatePicker,
  Input,
  InputNumber,
  Radio,
  Select,
  Slider,
  Switch,
  TreeSelect,
  Upload,
  Rate,
} from "antd";
import { UploadOutlined } from "@ant-design/icons";

const antdItem = {
  input: {
    type: "input",
    StandardInput: Input,
    configs: {
      fieldProperties: {
        name: "input",
        label: "标题",
        initialValue: undefined,
        noStyle: false,
        hidden: false,
        extra: "",
        rules: [],
        // rules: [{ required: true, message: "请输入标题！" }],
      },
      componentProperties: {
        addonBefore: "",
        addonAfter: "",
        prefix: "",
        suffix: "",
        disabled: false,
        placeholder: "请输入",
        allowClear: false,
        maxLength: 20,
        bordered: true,
        showCount: false,
      },
      styles: {
        width: "",
        height: "",
        margin: undefined,
        padding: undefined,
        border: undefined,
        borderRadius: undefined,
      },
    },
  },
  inputTexArea: {
    type: "inputTexArea",
    StandardInput: Input.TextArea,
    configs: {
      fieldProperties: {
        name: "inputTexArea",
        label: "多行文本",
        initialValue: undefined,
        noStyle: false,
        hidden: false,
        extra: "",
        rules: [],
        // rules: [{ required: true, message: "请输入文本！" }],
      },
      componentProperties: {
        disabled: false,
        placeholder: "请输入",
        rows: 4,
        autoSize: false,
        allowClear: false,
        maxLength: 20,
        showCount: false,
        bordered: true,
      },
      styles: {
        width: "",
        height: "",
        margin: undefined,
        padding: undefined,
        border: undefined,
        borderRadius: undefined,
      },
    },
  },
  inputNumber: {
    type: "inputNumber",
    StandardInput: InputNumber,
    configs: {
      fieldProperties: {
        name: "inputNumber",
        label: "数字",
        initialValue: undefined,
        noStyle: false,
        hidden: false,
        rules: [],
        // rules: [{ required: true, message: "请输入数字！" }],
      },
      componentProperties: {
        disabled: false,
        placeholder: "请输入",
        max: 10,
        min: 0,
        bordered: true,
        step: "1",
        controls: true,
        decimalSeparator: 0,
        precision: 0,
        readOnly: false,
        keyboard: true,
        autoFocus: false,
      },
      styles: {
        width: "",
        height: "",
        margin: undefined,
        padding: undefined,
        border: undefined,
        borderRadius: undefined,
      },
    },
  },
  select: {
    type: "select",
    StandardInput: Select,
    configs: {
      fieldProperties: {
        name: "select",
        label: "选项",
        initialValue: undefined,
        noStyle: false,
        hidden: false,
        rules: [],
        // rules: [{ required: true, message: "请选择！" }],
      },
      componentProperties: {
        disabled: false,
        placeholder: "请选择",
        options: [
          { label: "A", value: 1 },
          { label: "B", value: 2 },
        ],
        bordered: true,
        allowClear: false,
        showArrow: true,
        showSearch: false,
        autoClearSearchValue: true,
        mode: undefined,
        optionFilterProp: "value",
        filterOption: true,
        defaultActiveFirstOption: true,
        dropdownMatchSelectWidth: true,
        listHeight: 256,
        maxTagCount: 10,
        maxTagTextLength: 0,
        defaultOpen: false,
        virtual: true,
        autoFocus: false,
      },
      styles: {
        width: "",
        height: "",
        margin: undefined,
        padding: undefined,
        border: undefined,
        borderRadius: undefined,
      },
    },
  },
  cascader: {
    type: "cascader",
    StandardInput: Cascader,
    configs: {
      fieldProperties: {
        name: "cascader",
        label: "联级选择",
        initialValue: [],
        noStyle: false,
        hidden: false,
        rules: [],
        // rules: [{ required: true, message: "请选择！" }],
      },
      componentProperties: {
        disabled: false,
        placeholder: "请选择",
        options: [
          {
            label: "A",
            value: 1,
            children: [
              {
                value: "nanjing",
                label: "Nanjing",
                children: [
                  {
                    label: "Zhong Hua Men",
                    value: "zhonghuamen",
                  },
                ],
              },
            ],
          },
          {
            label: "B",
            value: 2,
            children: [
              {
                label: "West Lake",
                value: "xihu",
              },
            ],
          },
        ],
        allowClear: true,
        showSearch: false,
        bordered: true,
        notFoundContent: "无数据",
        className: "",
        changeOnSelect: false,
        expandTrigger: "click",
        autoFocus: false,
      },
      styles: {
        width: "",
        height: "",
        margin: undefined,
        padding: undefined,
        border: undefined,
        borderRadius: undefined,
      },
    },
  },
  treeSelect: {
    type: "treeSelect",
    StandardInput: TreeSelect,
    configs: {
      fieldProperties: {
        name: "treeSelect",
        label: "树选择",
        initialValue: undefined,
        noStyle: false,
        hidden: false,
        rules: [],
        // rules: [{ required: true, message: "请选择！" }],
      },
      componentProperties: {
        disabled: false,
        placeholder: "请选择",
        treeData: [
          {
            title: "A",
            value: 1,
            children: [
              {
                title: "Nanjing",
                value: "nanjing",
                children: [
                  {
                    title: "Zhong Hua Men",
                    value: "zhonghuamen",
                  },
                ],
              },
            ],
          },
          {
            title: "B",
            value: 2,
            children: [
              {
                title: "West Lake",
                value: "xihu",
              },
            ],
          },
        ],
        allowClear: false,
        autoClearSearchValue: true,
        showArrow: true,
        showSearch: false,
        bordered: true,
        multiple: false,
        treeCheckable: false,
        treeCheckStrictly: false,
        treeDefaultExpandAll: false,
        dropdownClassName: "",
        dropdownMatchSelectWidth: true,
        listHeight: 256,
        virtual: true,
      },
      styles: {
        width: "",
        height: "",
        margin: undefined,
        padding: undefined,
        border: undefined,
        borderRadius: undefined,
      },
    },
  },
  checkboxGroup: {
    type: "checkboxGroup",
    StandardInput: Checkbox.Group,
    configs: {
      fieldProperties: {
        name: "checkboxGroup",
        label: "多选",
        initialValue: [],
        noStyle: false,
        hidden: false,
        rules: [],
        // rules: [{ required: true, message: "请选择！" }],
      },
      componentProperties: {
        disabled: false,
        options: Object(),
      },
      styles: {
        width: "",
        height: "",
        margin: undefined,
        padding: undefined,
        border: undefined,
        borderRadius: undefined,
      },
    },
  },
  checkbox: {
    type: "checkbox",
    StandardInput: Checkbox,
    configs: {
      fieldProperties: {
        name: "checkbox",
        label: "勾选开关",
        initialValue: false,
        noStyle: false,
        hidden: false,
        rules: [],
        // rules: [{ required: true, message: "请选择！" }],
      },
      componentProperties: {
        disabled: false,
        indeterminate: false,
        autoFocus: false,
      },
      styles: {
        width: "",
        height: "",
        margin: undefined,
        padding: undefined,
        border: undefined,
        borderRadius: undefined,
      },
    },
  },
  radioGroup: {
    type: "radioGroup",
    StandardInput: Radio.Group,
    configs: {
      fieldProperties: {
        name: "radioGroup",
        label: "单选",
        initialValue: undefined,
        noStyle: false,
        hidden: false,
        rules: [],
        // rules: [{ required: true, message: "请选择！" }],
      },
      componentProperties: {
        disabled: false,
        options: [
          { label: "A", value: 1 },
          { label: "B", value: 2 },
        ],
        autoFocus: false,
        optionType: "default",
        buttonStyle: "outline",
      },
      styles: {
        width: "",
        height: "",
        margin: undefined,
        padding: undefined,
        border: undefined,
        borderRadius: undefined,
      },
    },
  },
  datePicker: {
    type: "datePicker",
    StandardInput: DatePicker,
    configs: {
      fieldProperties: {
        name: "datePicker",
        label: "日期",
        noStyle: false,
        hidden: false,
        rules: [],
        // rules: [{ required: true, message: "请选择日期！" }],
      },
      componentProperties: {
        disabled: false,
        placeholder: "请选择",
        // picker: 'date',
        allowClear: true,
        bordered: true,
        showNow: true,
        showTime: false,
        showToday: true,
        className: "",
        dropdownClassName: "",
        inputReadOnly: false,
        autoFocus: false,
      },
      styles: {
        width: "",
        height: "",
        margin: undefined,
        padding: undefined,
        border: undefined,
        borderRadius: undefined,
      },
    },
  },
  rangePicker: {
    type: "rangePicker",
    StandardInput: DatePicker.RangePicker,
    configs: {
      fieldProperties: {
        name: "rangePicker",
        label: "日期",
        noStyle: false,
        hidden: false,
        rules: [],
        // rules: [{ required: true, message: "请选择日期！" }],
      },
      componentProperties: {
        disabled: false,
        // picker: 'day',
        format: "",
      },
      styles: {
        width: "",
        height: "",
        margin: undefined,
        padding: undefined,
        border: undefined,
        borderRadius: undefined,
      },
    },
  },
  upload: {
    type: "upload",
    StandardInput: Upload,
    configs: {
      fieldProperties: {
        name: "upload",
        label: "上传",
        noStyle: false,
        hidden: false,
        rules: [],
        // rules: [{ required: true, message: "请上传！" }],
      },
      componentProperties: {
        disabled: false,
        method: "post",
        action: "https://www.baidu.com",
        accept: "",
        listType: "text",
        showUploadList: true,
        directory: false,
        maxCount: 10,
        multiple: false,
        name: "file",
        withCredentials: false,
        openFileDialogOnClick: true,
      },
      styles: {
        width: "",
        height: "",
        margin: undefined,
        padding: undefined,
        border: undefined,
        borderRadius: undefined,
      },
      extra: {
        childrenNode: () => <Button icon={<UploadOutlined />}>上传</Button>,
      },
    },
  },
  switch: {
    type: "switch",
    StandardInput: Switch,
    configs: {
      fieldProperties: {
        name: "switch",
        label: "开关",
        initialValue: false,
        noStyle: false,
        hidden: false,
        rules: [],
        // rules: [{ required: false, message: "请选择" }],
      },
      componentProperties: {
        disabled: false,
        className: "",
        autoFocus: false,
        checkedChildren: "",
        unCheckedChildren: "",
        loading: false,
      },
      styles: {
        width: "",
        height: "",
        margin: undefined,
        padding: undefined,
        border: undefined,
        borderRadius: undefined,
      },
    },
  },
  button: {
    type: "button",
    StandardInput: Button,
    configs: {
      fieldProperties: {
        name: "button",
        label: "按钮",
        noStyle: false,
        hidden: false,
      },
      componentProperties: {
        disabled: false,
        type: Object(),
        htmlType: "submit",
        block: false,
        danger: false,
        ghost: false,
        shape: undefined,
        loading: false,
      },
      styles: {
        width: "",
        height: "",
        margin: undefined,
        padding: undefined,
        border: undefined,
        borderRadius: undefined,
      },
      extra: {
        childrenNode: "确定",
      },
    },
  },
  slider: {
    type: "slider",
    StandardInput: Slider,
    configs: {
      fieldProperties: {
        name: "slider",
        label: "滑动输入",
        initialValue: undefined,
        noStyle: false,
        hidden: false,
        rules: [],
        // rules: [{ required: true, message: "请输入！" }],
      },
      componentProperties: {
        disabled: false,
        allowClear: false,
        max: 100,
        min: 0,
        dots: false,
        included: true,
        reverse: false,
        step: 1,
        tooltipPlacement: undefined,
        tooltipVisible: false,
        vertical: false,
      },
      styles: {
        width: "",
        height: "",
        margin: undefined,
        padding: undefined,
        border: undefined,
        borderRadius: undefined,
      },
    },
  },
  rate: {
    type: "rate",
    StandardInput: Rate,
    configs: {
      fieldProperties: {
        name: "rate",
        label: "评分",
        initialValue: undefined,
        noStyle: false,
        hidden: false,
        rules: [],
      },
      componentProperties: {
        allowClear: true,
        disabled: false,
        allowHalf: false,
        count: 5,
        tooltips: "",
      },
      styles: {
        width: "",
        height: "",
        margin: undefined,
        padding: undefined,
        border: undefined,
        borderRadius: undefined,
      },
    },
  },
};

export const antdItemConfig = {
  antd: antdItem,
};
